/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pondoku;

/**
 *
 * @author HP
 */
public class bahasa extends javax.swing.JFrame {

    /**
     * Creates new form bahasa
     */
    public bahasa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        raudhatulhasanah = new javax.swing.JLabel();
        alanwar = new javax.swing.JLabel();
        elqolam = new javax.swing.JLabel();
        darunnajah = new javax.swing.JLabel();
        gontor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        raudhatulhasanah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bahasa/5.png"))); // NOI18N
        raudhatulhasanah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raudhatulhasanahMouseClicked(evt);
            }
        });
        jPanel1.add(raudhatulhasanah, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 170, 390));

        alanwar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bahasa/4.png"))); // NOI18N
        alanwar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alanwarMouseClicked(evt);
            }
        });
        jPanel1.add(alanwar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 160, 410));

        elqolam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bahasa/3.png"))); // NOI18N
        elqolam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elqolamMouseClicked(evt);
            }
        });
        jPanel1.add(elqolam, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 170, 390));

        darunnajah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bahasa/2.png"))); // NOI18N
        darunnajah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                darunnajahMouseClicked(evt);
            }
        });
        jPanel1.add(darunnajah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, 390));

        gontor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bahasa/1.png"))); // NOI18N
        gontor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gontorMouseClicked(evt);
            }
        });
        jPanel1.add(gontor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 170, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bahasa/bahasachoose.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gontorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gontorMouseClicked
        // TODO add your handling code here:
        gontor g = new gontor();
        g.setLocationRelativeTo(null);
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gontorMouseClicked

    private void darunnajahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_darunnajahMouseClicked
        // TODO add your handling code here:
        darunnajah dn = new darunnajah();
        dn.setLocationRelativeTo(null);
        dn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_darunnajahMouseClicked

    private void elqolamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elqolamMouseClicked
        // TODO add your handling code here:
        elqolam eq = new elqolam();
        eq.setLocationRelativeTo(null);
        eq.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_elqolamMouseClicked

    private void alanwarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alanwarMouseClicked
        // TODO add your handling code here:
        alanwar anwar = new alanwar();
        anwar.setLocationRelativeTo(null);
        anwar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_alanwarMouseClicked

    private void raudhatulhasanahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raudhatulhasanahMouseClicked
        // TODO add your handling code here:
        raudhatulhasanah rh = new raudhatulhasanah();
        rh.setLocationRelativeTo(null);
        rh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_raudhatulhasanahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                bahasa bahasa = new bahasa();
                bahasa.setLocationRelativeTo(null);
                bahasa.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alanwar;
    private javax.swing.JLabel darunnajah;
    private javax.swing.JLabel elqolam;
    private javax.swing.JLabel gontor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel raudhatulhasanah;
    // End of variables declaration//GEN-END:variables
}
