/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pondoku;

/**
 *
 * @author HP
 */
public class jurusan extends javax.swing.JFrame {

    /**
     * Creates new form jurusan
     */
    public jurusan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kitabChoose = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bahasaChoose = new javax.swing.JLabel();
        alquranChoose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kitabChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kitab.png"))); // NOI18N
        kitabChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitabChooseMouseClicked(evt);
            }
        });
        jPanel1.add(kitabChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 300, 350));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 190, 290));

        bahasaChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bahasa.png"))); // NOI18N
        bahasaChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bahasaChooseMouseClicked(evt);
            }
        });
        jPanel1.add(bahasaChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 300, 340));

        alquranChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kuran.png"))); // NOI18N
        alquranChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alquranChooseMouseClicked(evt);
            }
        });
        jPanel1.add(alquranChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 430, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jurusan.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alquranChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alquranChooseMouseClicked
        // TODO add your handling code here:
        modern md = new modern();
        md.setLocationRelativeTo(null);
        md.setVisible(true);
        this.setVisible(false);
        System.out.println("modern form berhasil");
    }//GEN-LAST:event_alquranChooseMouseClicked

    private void bahasaChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bahasaChooseMouseClicked
        // TODO add your handling code here:
        bahasa bh = new bahasa();
        bh.setLocationRelativeTo(null);
        bh.setVisible(true);
        this.setVisible(false);
        System.out.println("bahasa form berhasil");
    }//GEN-LAST:event_bahasaChooseMouseClicked

    private void kitabChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitabChooseMouseClicked
        // TODO add your handling code here:
        kitab kt = new kitab();
        kt.setLocationRelativeTo(null);
        kt.setVisible(true);
        this.setVisible(false);
        System.out.println("kitab form berhasil");
    }//GEN-LAST:event_kitabChooseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jurusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jurusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jurusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jurusan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jurusan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alquranChoose;
    private javax.swing.JLabel bahasaChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kitabChoose;
    // End of variables declaration//GEN-END:variables
}
