/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pondoku;

/**
 *
 * @author HP
 */
public class kitab extends javax.swing.JFrame {

    /**
     * Creates new form bahasa
     */
    public kitab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        almakiyah = new javax.swing.JLabel();
        alkahfi = new javax.swing.JLabel();
        alhikmah = new javax.swing.JLabel();
        almunawwir = new javax.swing.JLabel();
        luqmaniyah = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        almakiyah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kitab/5.png"))); // NOI18N
        almakiyah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                almakiyahMouseClicked(evt);
            }
        });
        jPanel1.add(almakiyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 170, 390));

        alkahfi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kitab/4.png"))); // NOI18N
        alkahfi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alkahfiMouseClicked(evt);
            }
        });
        jPanel1.add(alkahfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 160, 410));

        alhikmah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kitab/3.png"))); // NOI18N
        alhikmah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alhikmahMouseClicked(evt);
            }
        });
        jPanel1.add(alhikmah, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 170, 390));

        almunawwir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kitab/2.png"))); // NOI18N
        almunawwir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                almunawwirMouseClicked(evt);
            }
        });
        jPanel1.add(almunawwir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, 390));

        luqmaniyah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kitab/1.png"))); // NOI18N
        luqmaniyah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                luqmaniyahMouseClicked(evt);
            }
        });
        jPanel1.add(luqmaniyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 170, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kitab/choosekitab.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luqmaniyahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_luqmaniyahMouseClicked
        // TODO add your handling code here:
        ponpesAluqmaniyah a = new ponpesAluqmaniyah();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_luqmaniyahMouseClicked

    private void almunawwirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_almunawwirMouseClicked
        // TODO add your handling code here:
        ponpesAlmunawwir b = new ponpesAlmunawwir();
        b.setLocationRelativeTo(null);
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_almunawwirMouseClicked

    private void alhikmahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alhikmahMouseClicked
        // TODO add your handling code here:
        ponpesAlhikmah c = new ponpesAlhikmah();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_alhikmahMouseClicked

    private void alkahfiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alkahfiMouseClicked
        // TODO add your handling code here:
        ponpesAlkahfi d = new ponpesAlkahfi();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_alkahfiMouseClicked

    private void almakiyahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_almakiyahMouseClicked
        // TODO add your handling code here:
        ponpesAlmakiyah e = new ponpesAlmakiyah();
        e.setLocationRelativeTo(null);
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_almakiyahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kitab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kitab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kitab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kitab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                kitab kitab = new kitab();
                kitab.setLocationRelativeTo(null);
                kitab.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alhikmah;
    private javax.swing.JLabel alkahfi;
    private javax.swing.JLabel almakiyah;
    private javax.swing.JLabel almunawwir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel luqmaniyah;
    // End of variables declaration//GEN-END:variables
}
